#cloud-config
repo_update: true
repo_upgrade: all
package_upgrade: true

packages:
  - glibc.i686
  - libstdc++.i686
  - tmux

write_files:
- encoding: b64
  content: £PREPARE
  path: /usr/bin/prepare.sh
  owner: root:root
  permissions: '0755'
- encoding: b64
  content: £SERVICE
  path: /etc/init.d/kf2server.sh
  owner: root:root
  permissions: '0777'
- encoding: b64
  content: £MONITOR
  path: /etc/init.d/monitor.sh
  owner: root:root
  permissions: '0777'

runcmd:
- /usr/bin/prepare.sh

power_state:
  mode: reboot
  timeout: 6000
  condition: true
